### PR TITLE
add echo-react-email directory

### PR DESCRIPTION
**Pull request by sumitsaurabh927**

### CODE REVIEW

**Comment by unicodeveloper** [comment]
@sumitsaurabh927 did you add an echo-examples directory?

**Comment by sumitsaurabh927** [comment]
@unicodeveloper yes I did. Shall I rename it to `echo-examples-react-email`?
image

**Comment by unicodeveloper** [comment]
No. I mean your `echo-react-email` directory needs to exist inside another directory called `echo-examples`. @sumitsaurabh927

**Comment by sumitsaurabh927** [comment]
My bad!
Let me rectify.

**Pull request closed without merging**
